Console.Clear();
Console.Write("Insert x1: ");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Insert y1: ");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Insert z1: ");
int z1 = Convert.ToInt32(Console.ReadLine());
Console.Write("Insert x2: ");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Insert y2: ");
int y2 = Convert.ToInt32(Console.ReadLine());
Console.Write("Insert z2: ");
int z2 = Convert.ToInt32(Console.ReadLine());
double result = Math.Sqrt(Math.Pow(x2 - x1, 2) + Math.Pow(y2 - y1, 2) + Math.Pow(z2 - z1, 2));
Console.WriteLine(result);